let panjang = Number(prompt(`masukkan panjang d1 (cm)`))
let lebar = Number(prompt("masukkan panjang d2 (cm)"))
let jumlahPanjangLebar = panjang * lebar
const luasJajarGenjang = 1/2 * jumlahPanjangLebar
alert( `Dengan panjang d1 ${panjang}cm, panjang d2 ${lebar}cm, maka luas belah ketupat dengan menggunakan rumus (L = ½ x d1 x d2) adalah
d1 = ${panjang}cm
d2 = ${lebar}cm
Luas Belah Ketupat =  1/2 x  d1 x d2
Luas Belah Ketupat = 1/2 x ${panjang}cm x  ${lebar}cm 
Luas Belah Ketupat = ${luasJajarGenjang}cm2 `)
